version: '3.8'

services:
  node:
    build:
      target: base
    command: yarn start:dev
    networks:
      - intranet
  mysql:
    container_name: mysql
    build:
      context: .
      dockerfile: /docker/mysql/Dockerfile
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    expose:
      - ${DATABASE_PORT}
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    networks:
      - intranet

networks:
  intranet:
    driver: bridge
