version: '3.8'

services:
  node:
    container_name: node
    build:
      context: .
      dockerfile: /docker/node/Dockerfile
      target: production
    volumes:
      - ./src:/usr/nok/src
      - ./nodemon.json:/usr/nok/nodemon.json
    env_file:
      - .env
    expose:
      - ${PORT}
    ports:
      - ${PORT}:${PORT}
    command: yarn start
    networks:
      - intranet
  mysql:
    container_name: mysql
    build:
      context: .
      dockerfile: /docker/mysql/Dockerfile
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    env_file:
      - .env
    expose:
      - ${DATABASE_PORT}
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    networks:
      - intranet

networks:
  intranet:
    driver: bridge
