version: '3.8'

services:
  node:
    container_name: node
    build:
      context: .
      dockerfile: /docker/node/Dockerfile
      target: production
    volumes:
      - ./src:/usr/nok/src
      - ./nodemon.json:/usr/nok/nodemon.json
    env_file:
      - .env
    expose:
      - ${PORT}
    ports:
      - ${PORT}:${PORT}
    command: yarn start
