const {
  DATABASE_DOMAIN,
  DATABASE_NAME,
  DATABASE_PASSWORD,
  DATABASE_PORT
} = process.env

process.stdout.write(
  `mysql://root:${DATABASE_PASSWORD}@${DATABASE_DOMAIN}:${DATABASE_PORT}/${DATABASE_NAME}`
)
